apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-developpement
  description: L'équipe de développement.
  namespace: default
  annotations:
    example.com/attribute: value
spec:
  type: team
  parent: company
  children:
    - team-frontend
    - team-backend
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-frontend
  description: L'équipe frontend responsable du développement de l'interface utilisateur.
  namespace: default
spec:
  type: team
  parent: team-developpement
  children: []  # Ajout de la propriété children
  members:
    - user:default/alice  # Ajout du namespace
    - user:default/bob  # Ajout du namespace
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-backend
  description: L'équipe backend responsable des API et des services.
  namespace: default
spec:
  type: team
  parent: team-developpement
  children: []  # Ajout de la propriété children
  members:
    - user:default/charlie  # Ajout du namespace
    - user:default/dave  # Ajout du namespace
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-api-comptes
  description: L'équipe responsable de l'API de gestion des comptes.
  namespace: default
spec:
  type: team
  parent: company
  children: []  # Ajout de la propriété children
  members:
    - user:john-doe
    - user:jane-doe
