apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: company
  namespace: default
  description: La compagnie qui possède plusieurs équipes.
  annotations:
    backstage.io/managed-by-location: url:https://github.com/younes-bami/backstage/blob/master/entities/company.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/younes-bami/backstage/blob/master/entities/company.yaml
spec:
  type: organization
  profile:
    displayName: Company Name
  children:
    - group:default/team-developpement
    - group:default/team-api-comptes
  members: []
